#country_capitals = {}
#print(country_capitals)
my_dict = {'name': 'Alice'}
value = my_dict['name']  
print(value)
my_dict['age'] = '25' 
print(my_dict)
my_dict['age'] = '30' 
print(my_dict)
#value = my_dict['height']  
#print(value)
dictionarykeys=my_dict.keys()
print(dictionarykeys)
dictionaryvalues=my_dict.values()
print(dictionaryvalues)


 #Python KeyError is raised when we try to access a key from dict which doesn't exist. 
 